
services:
    # nginx    
    router:
        image: nginx:latest        
        volumes:
            - ${WEBAPP_STORAGE_HOME}/nginx-default.conf:/etc/nginx/conf.d/default.conf            
            # - ${WEBAPP_STORAGE_HOME}/certs/localhost.crt:/etc/nginx/ssl/localhost.crt
            # - ${WEBAPP_STORAGE_HOME}/certs/localhost.key:/etc/nginx/ssl/localhost.key     
        ports:
            - "80:80"
    # php
    php-server:
        image: zkornas/php-server:latest
        environment:
            LOGGLY_TOKEN: "${LOGGLY_TOKEN}"
        extra_hosts:
            - host.docker.internal:host-gateway
    # mysql
    mysql-database:
        image: mysql:latest
        volumes:
            - mysqldata:/var/lib/mysql
            - ${WEBAPP_STORAGE_HOME}/database:/docker-entrypoint-initdb.d            
        restart: always                    
        command: --init-file /docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
        ports:
            - "3306:3306"
            
volumes:
    mysqldata:
